/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fr.ufrsciencestech.panier;

/**
 *
 * @author sc364347
 */
public class JHM extends javax.swing.JFrame {

    /**
     * Creates new form JHM
     */
    public JHM() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        plusJHM = new javax.swing.JButton();
        comboJHM = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        textJHM = new javax.swing.JTextArea();
        moinsJHM = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        plusJHM.setText("+");
        plusJHM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusJHMActionPerformed(evt);
            }
        });
        jPanel1.add(plusJHM, java.awt.BorderLayout.LINE_START);

        comboJHM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboJHM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboJHMActionPerformed(evt);
            }
        });
        jPanel1.add(comboJHM, java.awt.BorderLayout.PAGE_END);

        textJHM.setEditable(false);
        textJHM.setColumns(20);
        textJHM.setRows(5);
        jScrollPane1.setViewportView(textJHM);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        moinsJHM.setText("-");
        moinsJHM.setActionCommand("textJHM");
        jPanel1.add(moinsJHM, java.awt.BorderLayout.LINE_END);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void plusJHMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusJHMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_plusJHMActionPerformed

    private void comboJHMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboJHMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboJHMActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JHM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JHM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JHM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JHM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JHM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboJHM;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton moinsJHM;
    private javax.swing.JButton plusJHM;
    private javax.swing.JTextArea textJHM;
    // End of variables declaration//GEN-END:variables
}
