/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package fr.ufrsciencestech.panier;

import java.util.Observable;
import java.util.Observer;

/**
 *
 * @author sc364347
 */
public class VueAWT extends java.awt.Frame implements Observer {

    /** Creates new form VueAWT */
    public VueAWT() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        button1 = new java.awt.Button();
        textField1 = new java.awt.TextField();
        button2 = new java.awt.Button();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        panel1.setLayout(new java.awt.GridLayout());

        button1.setLabel("button1");
        panel1.add(button1);

        textField1.setText("textField1");
        panel1.add(textField1);

        button2.setLabel("button2");
        panel1.add(button2);

        add(panel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    /**
    * @param args the command line arguments
    */
    public void addControler(Controler c){
        getButton2().addActionListener(c);
        getButton1().addActionListener(c);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private java.awt.Button button2;
    private java.awt.Panel panel1;
    private java.awt.TextField textField1;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the button1
     */
    public java.awt.Button getButton1() {
        return button1;
    }

    /**
     * @return the button2
     */
    public java.awt.Button getButton2() {
        return button2;
    }

    @Override
    public void update(Observable o, Object arg) {
        Panier p=(Panier)o;
        textField1.setText(((Integer)p.getSize()).toString()); //To change body of generated methods, choose Tools | Templates.
    }

}
